[project]
name = "djangoproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Akram Huseynli", email = "huseynliakramdevv1@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "django>=6.1",
]

[project.scripts]
djangoproject = "djangoproject:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
